spring:
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:postgresql://postgres-server:5432/coach_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/master-changelog.yml
    enabled: true
    default-schema: public
    drop-first: false
    contexts: dev, test, prod
    liquibase-schema: public
    database-change-log-lock-table: databasechangeloglock
    database-change-log-table: databasechangelog

grpc:
  notification-service:
    host: ${GRPC_NOTIFICATION_SERVICE_HOST}
    port: ${GRPC_NOTIFICATION_SERVICE_PORT}
